In [1]:
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
import random

In [2]:
set1 = [1, 2, 3]
lab_set = [0, 1]

n_exmp = 20

var1 = np.asarray([random.choice(set1) for ix in range(n_exmp)])
var2 = np.asarray([random.choice(set1) for ix in range(n_exmp)])
lab = np.asarray([random.choice(lab_set) for ix in range(n_exmp)])

print var1
print var2
print lab

[2 1 3 3 1 1 1 2 1 2 2 2 3 2 2 3 2 3 1 1]
[1 3 2 3 1 1 2 1 2 3 1 1 3 2 3 1 3 2 3 2]
[0 0 1 0 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 1]


In [3]:
def probability(val, n_sample):
    cnt = 0
    
    for ix in range(n_sample.shape[0]):
        if n_sample[ix] == val:
            cnt += 1
    return float(cnt)/float(n_sample.shape[0])


def conditional_probability(c1, data, c2):
    #c2 = label
    #c1 = data point in data
    n = lab.shape[0]
    count_c2 = 0
    count_c1_c2 = 0
    for ix in range(n):
        if lab[ix] == c2:
            count_c2 += 1
            if lab[ix] == c2 and data[ix] == c1:
                count_c1_c2 += 1
    return float(count_c1_c2)/float(count_c2)
            

print probability(1, var2)

0.35


In [4]:
def classify(inp):
    # for given input
    # decide probability for class 0
    
    prod_cond_prob = 1
    prod_pos_prob = 1
    
    prod_cond_prob *= conditional_probability(inp[0], var1, 0)   #6/12
    prod_cond_prob *= conditional_probability(inp[1], var2, 0)   #5/12
    
    prod_pos_prob *= probability(inp[0], var1)   #8/20
    prod_pos_prob *= probability(inp[1], var2)   #7/20
    
    #       12/20            * 6/12*5/12      /8/20*7/20
    p0 = probability(0, lab) * prod_cond_prob / prod_pos_prob     #0.8928
    
    
    
    prod_cond_prob = 1
    prod_pos_prob = 1
    
    prod_cond_prob *= conditional_probability(inp[0], var1, 1)  #2/8
    prod_cond_prob *= conditional_probability(inp[1], var2, 1)  #2/8
    
    print conditional_probability(inp[0], var1, 1)
    print conditional_probability(inp[1], var2, 1)
    
    prod_pos_prob *= probability(inp[0], var1)   #8/20
    prod_pos_prob *= probability(inp[1], var2)   #7/20
    
    print probability(inp[0], var1)
    print probability(inp[1], var2)

    #          8/20           *   2/8*2/8       /  8/20*7*20
    p1 = (probability(1, lab) * prod_cond_prob) / prod_pos_prob    #0.178
    
    return p0, p1

In [5]:
print var1
print var2
print lab

classify([2, 3])

[2 1 3 3 1 1 1 2 1 2 2 2 3 2 2 3 2 3 1 1]
[1 3 2 3 1 1 2 1 2 3 1 1 3 2 3 1 3 2 3 2]
[0 0 1 0 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 1]
0.25
0.25
0.4
0.35


(0.8928571428571429, 0.1785714285714286)

In [6]:
import sklearn
import pandas as pd
from sklearn.naive_bayes import GaussianNB

In [7]:
ds = pd.read_csv('/home/rupalibhati/CB-Perceptron/Class_7/train.csv')
data_X = ds.values[:10000, 1:]
data_y = ds.values[:10000, 0]

test_X = ds.values[10000:15000, 1:]
test_y = ds.values[10000:15000, 0]

print data_X.shape, test_X.shape
print data_y.shape, test_y.shape

(10000, 784) (5000, 784)
(10000,) (5000,)


In [8]:
gnb = GaussianNB()

gnb.fit(data_X, data_y)

gnb.score(test_X, test_y)

0.55820000000000003

In [9]:
from sklearn.decomposition import PCA

pca = PCA(n_components=319)

dt = pca.fit_transform(ds.values[:15000, 1:])


In [10]:
trans_X = dt[:10000, :]
test_trans_X = dt[10000:, :]

print trans_X.shape

(10000, 319)


In [11]:
gnb = GaussianNB()

gnb.fit(trans_X, data_y)

gnb.score(test_trans_X, test_y)

0.78979999999999995